name = "ga4-analytics-proxy"
compatibility_date = "2025-09-21"

# Replace with your actual domain
route = "tyyi.net/*"

# Environment variables - replace with your actual values
vars = { 
  GA_MEASUREMENT_ID = "G-XXXXXXXXXX", 
  GA_API_SECRET = "your_api_secret_here" 
}

# Build configuration
[build]
upload = { format = "service-worker" }
